### PR TITLE
Update for remark@7, gemoji@4

### PR DESCRIPTION
**Pull request by wooorm**
👋

Note: `tortue.me` doesn’t work anymore, so it’s now required to pass a `base` in `options`.
It’s also possible to pass `extname`, to define the end of the URL as well.

### CODE REVIEW

**Comment by jackycute** [comment]
Thanks @wooorm 
Also remind me the `tortue.me` doesn't work anymore.

**Comment by wooorm** [comment]
Same here!

**Comment by jackycute** [comment]
Done 😄

**Comment by wooorm** [comment]
Awesome, thanks!

**Pull request merged**
